### ISSUE TITLE
URL GET parameters

### ISSUE THREAD

**Issue by rpsoft** [actuallymentor/react-frontend-boilerplate#6]
Hi @actuallymentor! I really like your boilerplate. Very solid work!.

Just one question, I cannot seem to find a way to access the parameters in the URL (GET), any ideas?

Kind regards,

**Comment by actuallymentor** [comment]
Thanks @rpsoft :)

I'm not sure what your question is. You can access the url of a page through `window.location`.

**Comment by rpsoft** [comment]
Thanks for getting in touch @actuallymentor!, and I didn't think about using window.location ( so thanks again!).

This should work, but there is a problem/issue (Unless I am not seeing something). Say you have a search system, and you want to reflect the textual query you submit through a textbox, on the url's get variables.

Unless you have something like react-router in the system to deal with the changes in URL appropriately, it would require to reload the whole page, which is not as nice. So I was wondering if you have something in your system to deal with that?

Kind regards

**Comment by actuallymentor** [comment]
Very true. I kept this boilerplate quite minimalistic but feel free to make a pull request for it!

**Comment by actuallymentor** [comment]
I'm closing this issue for now. If you don't want to use a router package, have a look at the [history.pushState](https://developer.mozilla.org/en-US/docs/Web/API/History_API) functionality of HTML5.
